---
title: "Linear Models"
author: "Jake Vettoretti"
date: "2025-11-06"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
nyc_airbnb
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

Perform a regression

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Clean then refit

```{r}
nyc_airbnb |> 
  count(borough)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),  #puts categories in order of how often they occur
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Look at `lm` stuff

```{r}
summary(fit)
#summary(fit)$coef
#coef(fit)
#fitted.values(fit)
```

Look at cleaner `lm` stuff
```{r}
fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(
    term = str_replace(term, "^borough", "Borough: "
                       )) |> 
  knitr::kable(digits = 3)
```





